---
# This handler needs to be above the "Restart etherpad" handler!
- name: Ensure etherpad dependencies are latest
  include_tasks: handlers/install_deps.yml

- name: Restart etherpad-lite
  service:
    name: etherpad-lite
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true
